# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  licenses: Apache-2.0
  images: |
    - name: kubectl
      image: docker.io/bitnami/kubectl:1.30.1-debian-12-r1
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r22
    - name: redis
      image: docker.io/bitnami/redis:7.2.5-debian-12-r0
    - name: redis-exporter
      image: docker.io/bitnami/redis-exporter:1.60.0-debian-12-r1
    - name: redis-sentinel
      image: docker.io/bitnami/redis-sentinel:7.2.5-debian-12-r0
apiVersion: v2
appVersion: 7.2.5
dependencies:
- name: common
  repository: "file://charts/common/"
  tags:
  - bitnami-common
  version: 2.x.x
description: App Platform quick start Helm chart for creating a Redis cluster
home: https://bitnami.com
icon: https://linode.github.io/apl-charts/icons/redis.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: quickstart-redis
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/redis
version: 19.5.3
