apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postgresql.fullname" . }}-allow-db-communication
  labels: {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      otomi.io/app: {{ include "postgresql.fullname" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: cnpg-system
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              otomi.io/app: {{ include "postgresql.fullname" . }}