apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: {{ include "spinapp.fullname" . }}
  labels: {{- include "spinapp.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  executor: containerd-shim-spin
  replicas: {{ .Values.replicaCount }}
  enableAutoscaling: {{ .Values.enableAutoscaling }}
  podLabels:
    sidecar.istio.io/inject: "false"
  {{- with .Values.resources }}
  resources: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.env }}
  variables: {{- toYaml . | nindent 12 }}
  {{- end }}
  {{- with .Values.volumeMounts }}
  volumeMounts:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.volumeMounts }}
  volumes:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  checks:
    {{- with .Values.livenessProbe }}
    liveness:
    {{- . | toYaml | nindent 6 }}
    {{- end }}
    {{- with .Values.readinessProbe }}
    readiness:   
    {{- . | toYaml | nindent 6 }}
    {{- end }}