apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "ksvc.fullnameOverride" . }}
  labels: {{- include "ksvc.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.ingress "cluster" }}
    serving.deployment.dev/visibility: cluster-local
    {{- end }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "{{ .Values.autoscaling.minReplicas }}"
        autoscaling.knative.dev/max-scale: "{{ .Values.autoscaling.maxReplicas }}"
        {{- with .Values.annotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "ksvc.fullnameOverride" . }}
      automountServiceAccountToken: false   
      containers:
        - name: {{ include "ksvc.fullnameOverride" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.containerPorts }}
          ports: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.secrets }}
          envFrom: {{- include "envFrom" . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:   
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts: {{- include "volumeMounts" . | trim | nindent 12 }}
      volumes: {{- include "volumes" . | trim | nindent 8 }}
