apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "ksvc.fullnameOverride" . }}
  labels: {{- include "ksvc.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.Annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
- name: harbor-pullsecret
{{- with .Values.serviceAccount.imagePullSecrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
automountServiceAccountToken: false
