apiVersion: v2
name: redis-ha
description: App Platform quick start Helm chart for creating a Redis high availability cluster
type: application
version: 1.0.0
appVersion: "8.2.1"
icon: https://linode.github.io/apl-charts/icons/redis.png
