apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullnameOverride" . }}
  labels: {{- include "deployment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports: {{- .Values.servicePorts | toYaml | nindent 4 }} 
  selector: {{- include "deployment.selectorLabels" . | nindent 4 }}