fullnameOverride: test

image:
  repository: otomi/nodejs-helloworld
  tag: v1.2.13

# servicePorts:
#   - port: 80
#     targetPort: http
#     protocol: TCP
#     name: http

containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP

serviceAccount:
  create: true
  name: test