apiVersion: v1
data:
  defaultPipelineRoot: ""
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: kfp-launcher
---
apiVersion: v1
data:
  ConMaxLifeTime: 120s
  DEFAULT_CACHE_STALENESS: ""
  LOG_LEVEL: info
  MAXIMUM_CACHE_STALENESS: ""
  appName: pipeline
  appVersion: {{ .Chart.AppVersion }}
  autoUpdatePipelineDefaultVersion: "true"
  objHost: {{ .Values.objectStorage.region }}.linodeobjects.com
  objRegion: {{ .Values.objectStorage.region }}
  objPort: "443"
  bucketName: {{ .Values.objectStorage.bucket }}
  cacheDb: cachedb
  cacheImage: gcr.io/google-containers/busybox
  cacheNodeRestrictions: "false"
  cronScheduleTimezone: UTC
  dbHost: mysql
  dbPort: "3306"
  dbType: mysql
  defaultPipelineRoot: ""
  mlmdDb: metadb
  mysqlHost: mysql
  mysqlPort: "3306"
  pipelineDb: mlpipeline
  warning: |
    1. Do not use kubectl to edit this configmap, because some values are used
    during kustomize build. Instead, change the configmap and apply the entire
    kustomize manifests again.
    2. After updating the configmap, some deployments may need to be restarted
    until the changes take effect. A quick way to restart all deployments in a
    namespace: `kubectl rollout restart deployment -n <your-namespace>`.
kind: ConfigMap
metadata:
  labels:
    application-crd-id: kubeflow-pipelines
  name: pipeline-install-config
---