apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kfp.fullname" . }}-allow
  labels: {{- include "kfp.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      otomi.io/app: {{ include "kfp.fullname" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ include "kfp.fullname" . }}