apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "ksvc.fullname" . }}
  labels: {{- include "ksvc.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.ingress "cluster" }}
    serving.deployment.dev/visibility: cluster-local
    {{- end }}
spec:
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations: {{- toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
      labels:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ksvc.fullname" . }}
      automountServiceAccountToken: false   
      containers:
        - name: {{ include "ksvc.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.containerPorts }}
          ports: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.secrets }}
          envFrom: {{- include "ksvc.envFrom" . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:   
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
