fullnameOverride: ""

labels: {}

annotations: {}

env:
  - name: HF_TOKEN
    valueFrom:
      secretKeyRef:
        name: hf-secret
        key: HF_TOKEN
        optional: false

args:
  - --model_name=llama3
  - --model_id=meta-llama/meta-llama-3-8b-instruct

resources:
  limits:
    cpu: "6"
    memory: 24Gi
    nvidia.com/gpu: "1"
  requests:
    cpu: "6"
    memory: 24Gi
    nvidia.com/gpu: "1"

metrics:
  enabled: true
  endpoints: []