apiVersion: v2
name: k8s-deployment-otel
description: App Platform quick start Helm chart for creating a Kubernetes Deployment with Open Telemetry Instrumentation
version: 1.2.0
appVersion: "2.0.0"
icon: https://linode.github.io/apl-charts/icons/otel.png