apiVersion: v1
kind: Service
metadata:
  name: {{ include "litellm-proxy.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "litellm-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "litellm-proxy.selectorLabels" . | nindent 4 }}
