{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "deployment.fullnameOverride" . }}
  labels: 
    prometheus: {{ .Release.Namespace }}
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels: {{- include "deployment.selectorLabels" . | nindent 6 }}
  {{- with .Values.serviceMonitor.endpoints }}
  endpoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}