{{- if .Values.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: {{ include "postgresql.fullname" . }}
    prometheus: {{ .Release.Namespace }}
  name: {{ include "postgresql.fullname" . }}
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels: {{- include "postgresql.selectorLabels" . | nindent 6 }}
{{- end }}