apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "otomi-knative-service.fullname" . }}
  labels: {{- include "ksvc.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
- name: harbor-pullsecret
{{- with .Values.serviceAccount.imagePullSecrets }}
{{- toYaml . | nindent 2 }}
{{- end }}
automountServiceAccountToken: false
