## Create a bucket and an Access Key in Linode.
## Create a sealedSecret and add the Access Key and Secret Key:
## name: kubeflow-pipelines-obj-keys
## keys:
##  accesskey:
##  secretkey:
objectStorage:
  ## The Linode Region where the bucket is created
  region: us-ord-1
  ## The name of the bucket
  bucket: mlpipeline
  insecure: false
  ## Adjust the secretName if a different name is used for the sealedSecrets.
  secretName: "kubeflow-pipelines-obj-keys"