## Create a bucket and an Access Key in Linode.
## Create a sealedSecret with the name "mlpipeline-minio-artifact"
## and add the Access Key and Secret Key:
## keys:
##  accesskey:
##  secretkey:
objectStorage:
  ## The Linode Region where the bucket is created
  region: ""
  ## The name of the bucket
  bucket: ""
  ## Adjust the secretName if a different name is used for the sealedSecrets.

cacheDeployer:
  resources:
    requests:
      cpu: 10m
      memory: 8Mi

cacheServer:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi

metadataEnvoy:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

metadataGrpc:
  resources:
    requests:
      cpu: 10m
      memory: 8Mi

metadataWriter:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

mlPipeline:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

mlPipelinePersistenceagent:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi

mlPipelineScheduledworkflow:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi

mlPipelineUi:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

mlPipelineViewer:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

mlPipelineVisualizationserver:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi

mysql:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  ## Create a SealedSecret with the following key/values
  ## password: ""
  ## username: root
  ## Add the name of the SealedSecret here
  secret: ""

workflowController:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi