apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spin-operator.fullname" . }}-manager-role
  labels:
  {{- include "spin-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - core.spinkube.dev
  resources:
  - spinappexecutors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.spinkube.dev
  resources:
  - spinappexecutors/finalizers
  verbs:
  - update
- apiGroups:
  - core.spinkube.dev
  resources:
  - spinappexecutors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.spinkube.dev
  resources:
  - spinapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.spinkube.dev
  resources:
  - spinapps/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spin-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spin-operator
    app.kubernetes.io/part-of: spin-operator
  {{- include "spin-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "spin-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "spin-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'