{
 "title": "CloudNativePG pgvector Dashboard",
 "tags": [
  "pgvector",
  "postgresql",
  "cloudnativepg"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cnpg_pg_postmaster_start_time, namespace)"
    }
   },
   {
    "name": "instances",
    "label": "Instance",
    "query": {
     "query": "label_values(cnpg_pg_postmaster_start_time{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 1, "w": 15, "x": 3, "y": 0 },
   "options": {
    "content": "# pgvector PostgreSQL Cluster\n\nMonitoring dashboard for PostgreSQL clusters with pgvector extension"
   }
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval])) + sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[$__interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "CPU Utilisation from Requests",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",  namespace=\"$namespace\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "description": "Memory Utilisation from Requests",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(max by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}))"
    }
   ]
  }
 ]
}