apiVersion: core.spinkube.dev/v1alpha1
kind: SpinAppExecutor
metadata:
  name: containerd-shim-spin
spec:
  createDeployment: true
  deploymentConfig:
    runtimeClassName: wasmtime-spin-v2
    installDefaultCACerts: true
    {{- if .Values.openTelemetry.enabled }}
    otel:
      exporter_otlp_traces_endpoint: "http://otel-collector-collector.otel.svc.cluster.local:4317"
    {{- end }}
