{{- if eq .Values.type "deploy" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload.fullname" . }}
  labels: {{- include "workload.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "workload.selectorLabels" . | nindent 4 }}
{{- end }}