apiVersion: v1
kind: Service
metadata:
  name: {{ include "otomi-k8s-deployment-with-otel.fullname" . }}
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports: {{- .Values.servicePorts | toYaml | nindent 4 }} 
  selector: {{- include "deployment.selectorLabels" . | nindent 4 }}