kind: pipeline
type: docker
name: helm-lint

# Use docker:dind for running kind
services:
  - name: kubernetes
    image: docker:dind
    privileged: true
    volumes:
    - name: dockersock
      path: /var/run

volumes:
  - name: dockersock
    temp: {}
  - name: kubeconfig
    temp: {}

steps:

- name: wait for docker
  image: alpine
  commands:
    - sleep 5

- name: create kind cluster
  image: otwld/drone-kind
  settings:
    verbose: 1
    cluster_name: "kind-default"
    hostname: "kubernetes" # Use same name as service`s name
    config: 'kind-config.yml'
  volumes:
    - name: dockersock
      path: /var/run
    - name: kubeconfig
      path: /root/.kube
  depends_on:
    - wait for docker

- name: lint & install chart
  image: quay.io/helmpack/chart-testing
  commands:
    - ct lint-and-install --chart-dirs . --charts .
  depends_on:
    - create kind cluster
  volumes:
    - name: kubeconfig
      path: /root/.kube

- name: delete kind cluster
  image: otwld/drone-kind
  settings:
    clean_only: true
  volumes:
    - name: dockersock
      path: /var/run
    - name: kubeconfig
      path: /root/.kube
  when:
    status:
      - success
      - failure
  depends_on:
    - lint & install chart

trigger:
  event:
    - push
    - pull_request
    - custom
  branch:
    - main

---
kind: pipeline
type: docker
name: publish


trigger:
  event:
    - promote
  branch:
    - main

steps:
  - name: publish helm chart to github pages
    image: otwld/drone-chart-releaser-github-pages
    settings:
      cr_token:
        from_secret: github_access_token
      skip_existing: true
      root_package: true
