{{- if .Values.dashboard }}
{{- $file := .Files.Get "grafana-dashboard/rabbitmq.json" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-{{ include "rabbitmq.fullname" . }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
    grafana_dashboard: "1"
    release: grafana-dashboards-{{ .Release.Namespace | trimPrefix "team-" }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  rabbitmq.json: |-
    {{- $file | nindent 4 }}
{{- end }}