{{- if .Values.dashboard }}
{{- $file := .Files.Get "grafana-dashboard/cnpg.json" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-{{ include "rabbitmq.fullname" . }}
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  cnpg.json: |-
    {{- $file | nindent 4 }}
{{- end }}