
{{- $ := . }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "rabbitmq.fullname" $ }}
  labels: {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "rabbitmq.selectorLabels" $ | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        # - podSelector:
        #     matchLabels: {{- include "rabbitmq.selectorLabels" $ | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              name: {{ $.Release.Namespace }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "rabbitmq.fullname" $ }}-allow-operator
  labels: {{- include "rabbitmq.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "rabbitmq.selectorLabels" $ | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: rabbitmq