{{- $ := . }}
{{- $clusterName := include "otomi-quickstart-rabbitmq.fullname" $ }}
{{- range $i, $queue := $.Values.queues }}
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ $clusterName }}-{{ $queue.name }} # name of this custom resource; does not have to the same as the actual queue name
spec:
  name: {{ $queue.name }} # name of the queue
  rabbitmqClusterReference:
    name: {{ include "otomi-quickstart-rabbitmq.fullname" $ }}
{{- with $queue.spec }}
  {{- $queue.spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}