apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqQueue
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  vhost: {{ .vhost | default "/" }}
  queue: {{ .name }}
  durable: {{ .durable | default true }}
  autoDelete: {{ .autoDelete | default false }}
  arguments:
{{- if .arguments }}
{{ toYaml .arguments | indent 4 }}
{{- end }}
  policy:
{{- if .policy }}
{{ toYaml .policy | indent 4 }}
{{- end }}
