apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ include "otomi-quickstart-rabbitmq.fullname" . }}
  labels:
    {{- include "otomi-quickstart-rabbitmq.labels" . | nindent 4 }}