{{- if .Values.apl.networkPolicies.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "redis-ha.fullname" . }}-allow-redis-communication
  labels: {{- include "labels.standard" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      otomi.io/app: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
{{- end }}