apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ include "inferenceService.fullname" . }}
  labels: {{- include "inferenceService.labels" . | nindent 6 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
  annotations:
    {{- if .Values.metrics.enabled }}
    serving.kserve.io/enable-prometheus-scraping: "true"
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
spec:
  predictor:
    minReplicas: 1
    model:
      env:
        - name: NIM_MODEL_PROFILE
          value: vllm-fp16-tp2
      modelFormat:
        name: nvidia-nim-llama3-8b-instruct
      {{- with .Values.resources }}
      resources: {{- . | toYaml | nindent 8 }}
      {{- end }}
      runtime: nvidia-nim-llama3-8b-instruct-1.0.0