
{{- if .Values.versionOne.configmap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployment.fullname" . }}-v1
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.versionOne.configmap.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}