apiVersion: v2
name: nvidia-nim-llama-3-8b
description: App Platform quick start nvidia-nim-llama-3-8b LLM
version: 1.0.0
icon: https://developers.google.com/static/profile/badges/playlists/nvidia-deploy-with-gen-ai/badge.svg