name: Helm Chart Render Test

on:
  # Trigger the action on pushes and pull requests
  push:

  pull_request:


jobs:
  render-helm-chart:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Helm CLI
      - name: Set up Helm
        uses: azure/setup-helm@v3

      # Step 3: Lint the Helm chart
      - name: Lint Helm Chart
        run: tests/lint_charts.sh  

      # Step 4: Render Helm Chart templates
      - name: Render Helm Templates
        run: tests/template-charts.sh
