
{{- if .Values.configmap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otomi-quickstart-k8s-deployment.fullname" . }}
  labels: {{- include "deployment.labels" . | nindent 4 }}
  {{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.configmap.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}